### ISSUE TITLE
Model Selection (SageMaker) 

### ISSUE THREAD

**Issue by BaselMalalla** [bahrain-uob/moe-questions-bank#10]

**Comment by fedaabd** [comment]
what are the ones we evaluated and what are the problems. 
instances/ Quotas/ code/ integrations/ quality of questions/ Language limitation. etc

**Comment by ALMUTAWAJ** [comment]
- Deployment through Jumpstart includes many models such as llama 3.1 8b, llama 3.1 8b instruct, llama 3.2 1B and more. 
- All of the mentioned models' response quality was low and inefficient. 
- We tried to deploy the same models mentioned above using the notebook instance, but we faced an error of health check timeout. 
- The same models tested outside SageMaker were efficient and had high-quality responses. 
- The last reached point was checking Amazon models in Bedrock.
