### ISSUE TITLE
Explore Bedrock

### ISSUE THREAD

**Issue by BaselMalalla** [bahrain-uob/moe-questions-bank#12]

**Comment by fedaabd** [comment]
I'm not sure if this task is accurate; explore bedrock for what ? This is to evaluate the Bedrock as main services vs sage maker vs other options like EC2. I would like to see the outcome or next steps/issues to be resolved

**Comment by BaselMalalla** [comment]
With Bedrock we are limited to Amazon Titan Models only. Their results were not terrible but not exciting too. We decided to keep them as a Plan B in case deploying with SageMaker or EC2 didn't work.

**Comment by Ebrahim23m** [comment]
we are going with Bedrock
