### ISSUE TITLE
Create S3 Bucket & Upload Documents

### ISSUE THREAD

**Issue by Exortix** [bahrain-uob/moe-questions-bank#6]

**Comment by Exortix** [comment]
Add S3 bucket: moe-questions-bank-main

**Comment by Mahmood-Alalwan** [comment]
Changed main S3 bucket to "bucket-ma"

**Comment by fedaabd** [comment]
Next steps to explore an option for :
1- bulk import to S3
2- bulk/automated "Name changes to avoid spaces"
