### ISSUE TITLE
Automate the frontend calling of the RAG based on the type of the material @Exortix

### ISSUE THREAD

**Issue by aishaaltemimi** [bahrain-uob/moe-questions-bank#63]
_Originally posted by @aishaaltemimi in https://github.com/bahrain-uob/moe-questions-bank/issues/54#issuecomment-2527470733_

**Comment by Exortix** [comment]
- [ ] Refactor the lambda code to handle Arabic subjects requests.
- [ ] Update the frontend to allow the user to request an Arabic exam.
Next steps
- [ ] Integrate the code with the deployed SST resources mentioned in #64
