### ISSUE TITLE
Creation of the code in SST for the arabic track @Exortix

### ISSUE THREAD

**Issue by aishaaltemimi** [bahrain-uob/moe-questions-bank#64]
- [ ] Creation of the code in SST for the arabic track @Exortix

_Originally posted by @aishaaltemimi in https://github.com/bahrain-uob/moe-questions-bank/issues/54#issuecomment-2527470904_

**Comment by Exortix** [comment]
The following tasks are required to be implemented with incorporation of access policies:
- [ ] Create s3 bucket for the knowledge base @Exortix 
- [ ] Create OpenSearch Serverless collection @Exortix 
- [ ] Create the index in collection @Exortix 
- [ ] Create the knowledgebase using Bedrock APIs @Exortix 
- [ ] Upload the necessary Arab101 files (past exams, materials) @Exortix 
- [ ] Automate synchronization process on knowledge base source updates. @Exortix 

May refer to this issue #45
