### ISSUE TITLE
Lambda function takes the document to Textract to extract the text

### ISSUE THREAD

**Issue by Exortix** [bahrain-uob/moe-questions-bank#7]

**Comment by Exortix** [comment]
Textract lambda function does not return the whole text from the file

**Comment by Exortix** [comment]
Add lambda function: extract-text

**Comment by Mahmood-Alalwan** [comment]
fixed issue with lambda code for extracting files, but used a different S3 and lambda 
"myfunctionMA" is the working textract lambda function now.

**Comment by fedaabd** [comment]
what is the conclusion; the lambda is working, but is this enough for the solution, or do we need to investigate further steps for the coming spring? Textract is an option; but we need to invest in arranging the format of the document or another service or approach.

**Comment by Mahmood-Alalwan** [comment]
lambda for textarct is fully functional and successfully stores the txt files in "extracted files" folder in the same s3 bucket.
for now this is not enough for our solution and further arranging or changing the format of the pdf files might be needed.
